runtime: python
env: flex

# Use a special gunicorn worker class to support websockets.
entrypoint: gunicorn -b 127.0.0.1:8080 -k flask_sockets.worker main:app

runtime_config:
  python_version: 3

# network:
#   session_affinity: true
  
readinessCheck:
  appStartTimeout: 3000s
  checkInterval: 5s
  failureThreshold: 2
  successThreshold: 2
  timeout: 4s
