version: '2'
services:
  bokehapp:
    build:
      context: .
      dockerfile: dashboard.Dockerfile
    ports:
      - '5006:5006'
    volumes:
      - './:/app'
  flaskapp:
    depends_on:
      - bokehapp
    build:
      context: .
      dockerfile: main.Dockerfile
    volumes:
      - './:/app'
    ports:
      - '8080:8080'
